# Taken from an example provided by prisma: https://github.com/prisma/prisma-examples

version: "3.7"
services:
  mongodb_container:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
